/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package proyecto.componentes;

import java.awt.Color;

/**
 *
 * @author ABEL
 */
public final class PanelArbol extends javax.swing.JPanel {
    Color bgColorInfo = new Color(20,184,166);
    Color bgColorLiga = new Color(15,118,110);
    Color bgColorPuntero = new Color(19,78,74);
    
    Color bgAVLColorInfo = new Color(168, 85, 247);
    Color bgAVLColorLiga = new Color(126, 34, 206);
    Color bgAVLColorPuntero = new Color(88, 28, 135);
    
    Color bgColorInfoInactivo = new Color(115,115,115);
    Color bgColorLigaInactivo = new Color(64,64,64);
    Color bgColorPunteroInactivo = new Color(23,23,23);
    
    Color bgColorInfoError = new Color(239, 68, 68);
    Color bgColorLigaError = new Color(185, 28, 28);
    Color bgColorPunteroError = new Color(127, 29, 29);
    
    /**
     * Creates new form PanelNodo
     * @param data
     */
    
    public PanelArbol(int data) {
        initComponents();
        valorInfo.setText(Integer.toString(data));
    }
    
    public PanelArbol(int data, String anterior, String siguiente, String id) {
        initComponents();
        this.setInactiveColors();

        valorInfo.setText(Integer.toString(data));
        ligaAnterior.setText(anterior);
        ligaSiguiente.setText(siguiente);
        puntero.setText(id);
    }
    public void setColorInfo(Color color) {
        bgInfo.setBackground(color);
    }

    public void setColorSiguiente(Color color) {
        bgSiguiente.setBackground(color);
    }
    
    public void setColorAnterior(Color color) {
        bgAnterior.setBackground(color);
    }

    public void setColorPuntero(Color color) {
        bgPuntero.setBackground(color);
    }
    
    public void setActiveColors(boolean esAVL) {
        this.setColorInfo(esAVL ? bgAVLColorInfo : bgColorInfo);
        this.setColorSiguiente(esAVL ? bgAVLColorLiga : bgColorLiga);
        this.setColorAnterior(esAVL ? bgAVLColorLiga : bgColorLiga);
        this.setColorPuntero(esAVL ? bgAVLColorPuntero : bgColorPuntero);
    }
    
    public void setInactiveColors() {
        this.setColorInfo(bgColorInfoInactivo);
        this.setColorSiguiente(bgColorLigaInactivo);
        this.setColorAnterior(bgColorLigaInactivo);
        this.setColorPuntero(bgColorPunteroInactivo);
    }
    
    public void setErrorColors() {
        this.setColorInfo(bgColorInfoError);
        this.setColorSiguiente(bgColorLigaError);
        this.setColorAnterior(bgColorLigaError);
        this.setColorPuntero(bgColorPunteroError);
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        bgNodo = new javax.swing.JPanel();
        bgPuntero = new javax.swing.JPanel();
        puntero = new javax.swing.JLabel();
        bgInfo = new javax.swing.JPanel();
        valorInfo = new javax.swing.JLabel();
        bgAnterior = new javax.swing.JPanel();
        ligaAnterior = new javax.swing.JLabel();
        bgSiguiente = new javax.swing.JPanel();
        ligaSiguiente = new javax.swing.JLabel();

        bgNodo.setBackground(new java.awt.Color(255, 255, 255));
        bgNodo.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        bgNodo.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        bgPuntero.setBackground(new java.awt.Color(19, 78, 74));
        bgPuntero.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        puntero.setFont(new java.awt.Font("Segoe UI", 1, 10)); // NOI18N
        puntero.setForeground(new java.awt.Color(255, 255, 255));
        puntero.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        puntero.setText("NULL");
        bgPuntero.add(puntero, new org.netbeans.lib.awtextra.AbsoluteConstraints(5, 0, 20, 20));

        bgNodo.add(bgPuntero, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 30, 30, 20));

        bgInfo.setBackground(new java.awt.Color(20, 184, 166));
        bgInfo.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        valorInfo.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        valorInfo.setForeground(new java.awt.Color(255, 255, 255));
        valorInfo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        valorInfo.setText("NULL");
        bgInfo.add(valorInfo, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 0, 70, 30));

        bgNodo.add(bgInfo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 90, 30));

        bgAnterior.setBackground(new java.awt.Color(15, 118, 110));
        bgAnterior.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        ligaAnterior.setFont(new java.awt.Font("Segoe UI", 1, 10)); // NOI18N
        ligaAnterior.setForeground(new java.awt.Color(255, 255, 255));
        ligaAnterior.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        ligaAnterior.setText("NULL");
        bgAnterior.add(ligaAnterior, new org.netbeans.lib.awtextra.AbsoluteConstraints(5, 0, 20, 20));

        bgNodo.add(bgAnterior, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 30, 30, 20));

        bgSiguiente.setBackground(new java.awt.Color(15, 118, 110));
        bgSiguiente.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        ligaSiguiente.setFont(new java.awt.Font("Segoe UI", 1, 10)); // NOI18N
        ligaSiguiente.setForeground(new java.awt.Color(255, 255, 255));
        ligaSiguiente.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        ligaSiguiente.setText("NULL");
        bgSiguiente.add(ligaSiguiente, new org.netbeans.lib.awtextra.AbsoluteConstraints(5, 0, 20, 20));

        bgNodo.add(bgSiguiente, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 30, 30, 20));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(bgNodo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(bgNodo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel bgAnterior;
    private javax.swing.JPanel bgInfo;
    private javax.swing.JPanel bgNodo;
    private javax.swing.JPanel bgPuntero;
    private javax.swing.JPanel bgSiguiente;
    private javax.swing.JLabel ligaAnterior;
    private javax.swing.JLabel ligaSiguiente;
    private javax.swing.JLabel puntero;
    private javax.swing.JLabel valorInfo;
    // End of variables declaration//GEN-END:variables
}
