/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package proyecto.componentes;
import java.awt.Color;

/**
 *
 * @author ABEL
 */
public class PanelNodo extends javax.swing.JPanel {

    /**
     * Creates new form PanelNodo
     * @param data
     */
    public PanelNodo(String data, String liga, String id) {
        initComponents();

        valorInfo.setText(data);
        valorLiga.setText(liga);
        puntero.setText(id);
    }

    public void setColorInfo(Color color) {
        bgInfo.setBackground(color);
    }

    public void setColorLiga(Color color) {
        bgLiga.setBackground(color);
    }

    public void setColorPuntero(Color color) {
        bgPuntero.setBackground(color);
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        bgNodo = new javax.swing.JPanel();
        bgLiga = new javax.swing.JPanel();
        valorLiga = new javax.swing.JLabel();
        bgPuntero = new javax.swing.JPanel();
        puntero = new javax.swing.JLabel();
        bgInfo = new javax.swing.JPanel();
        valorInfo = new javax.swing.JLabel();

        bgNodo.setBackground(new java.awt.Color(255, 255, 255));
        bgNodo.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        bgNodo.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        bgLiga.setBackground(new java.awt.Color(67, 56, 202));
        bgLiga.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        valorLiga.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        valorLiga.setForeground(new java.awt.Color(255, 255, 255));
        valorLiga.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        valorLiga.setText("NULL");
        bgLiga.add(valorLiga, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 40, -1));

        bgNodo.add(bgLiga, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 0, 60, 40));

        bgPuntero.setBackground(new java.awt.Color(49, 46, 129));
        bgPuntero.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        puntero.setFont(new java.awt.Font("Segoe UI", 1, 10)); // NOI18N
        puntero.setForeground(new java.awt.Color(255, 255, 255));
        puntero.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        puntero.setText("NULL");
        bgPuntero.add(puntero, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 0, 120, 20));

        bgNodo.add(bgPuntero, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 40, 140, 20));

        bgInfo.setBackground(new java.awt.Color(99, 102, 241));
        bgInfo.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        valorInfo.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        valorInfo.setForeground(new java.awt.Color(255, 255, 255));
        valorInfo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        valorInfo.setText("NULL");
        bgInfo.add(valorInfo, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 60, -1));

        bgNodo.add(bgInfo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 80, 40));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(bgNodo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(bgNodo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel bgInfo;
    private javax.swing.JPanel bgLiga;
    private javax.swing.JPanel bgNodo;
    private javax.swing.JPanel bgPuntero;
    private javax.swing.JLabel puntero;
    private javax.swing.JLabel valorInfo;
    private javax.swing.JLabel valorLiga;
    // End of variables declaration//GEN-END:variables
}
