/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package proyecto.componentes;

/**
 *
 * @author ABEL
 */
public class PanelNodoDoble extends javax.swing.JPanel {

    /**
     * Creates new form PanelNodo
     * @param data
     */
    public PanelNodoDoble(String data, String anterior, String siguiente, String id) {
        initComponents();

        valorInfo.setText(data);
        ligaAnterior.setText(anterior);
        ligaSiguiente.setText(siguiente);
        puntero.setText(id);
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        bgNodo = new javax.swing.JPanel();
        bgAnterior = new javax.swing.JPanel();
        ligaAnterior = new javax.swing.JLabel();
        bgPuntero = new javax.swing.JPanel();
        puntero = new javax.swing.JLabel();
        bgInfo = new javax.swing.JPanel();
        valorInfo = new javax.swing.JLabel();
        bgSiguiente = new javax.swing.JPanel();
        ligaSiguiente = new javax.swing.JLabel();

        bgNodo.setBackground(new java.awt.Color(255, 255, 255));
        bgNodo.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        bgNodo.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        bgAnterior.setBackground(new java.awt.Color(15, 118, 110));
        bgAnterior.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        ligaAnterior.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        ligaAnterior.setForeground(new java.awt.Color(255, 255, 255));
        ligaAnterior.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        ligaAnterior.setText("NULL");
        bgAnterior.add(ligaAnterior, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 40, -1));

        bgNodo.add(bgAnterior, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 60, 40));

        bgPuntero.setBackground(new java.awt.Color(19, 78, 74));
        bgPuntero.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        puntero.setFont(new java.awt.Font("Segoe UI", 1, 10)); // NOI18N
        puntero.setForeground(new java.awt.Color(255, 255, 255));
        puntero.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        puntero.setText("NULL");
        bgPuntero.add(puntero, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 0, 180, 20));

        bgNodo.add(bgPuntero, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 40, 200, 20));

        bgInfo.setBackground(new java.awt.Color(20, 184, 166));
        bgInfo.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        valorInfo.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        valorInfo.setForeground(new java.awt.Color(255, 255, 255));
        valorInfo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        valorInfo.setText("NULL");
        bgInfo.add(valorInfo, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 60, -1));

        bgNodo.add(bgInfo, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 0, 80, 40));

        bgSiguiente.setBackground(new java.awt.Color(15, 118, 110));
        bgSiguiente.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        ligaSiguiente.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        ligaSiguiente.setForeground(new java.awt.Color(255, 255, 255));
        ligaSiguiente.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        ligaSiguiente.setText("NULL");
        bgSiguiente.add(ligaSiguiente, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 40, -1));

        bgNodo.add(bgSiguiente, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 0, 60, 40));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(bgNodo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(bgNodo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel bgAnterior;
    private javax.swing.JPanel bgInfo;
    private javax.swing.JPanel bgNodo;
    private javax.swing.JPanel bgPuntero;
    private javax.swing.JPanel bgSiguiente;
    private javax.swing.JLabel ligaAnterior;
    private javax.swing.JLabel ligaSiguiente;
    private javax.swing.JLabel puntero;
    private javax.swing.JLabel valorInfo;
    // End of variables declaration//GEN-END:variables
}
