/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package proyecto;

import proyecto.vistas.*;
import java.awt.BorderLayout;
import java.awt.Color;
import javax.swing.JPanel;

/**
 *
 * @author ABEL
 */
public class Bienvenido extends javax.swing.JPanel {
    private JPanel itemActivo = null;

    Color menuItemBg = new Color(50,51,128);
    Color menuItemBgHover = new Color(54, 52, 159);
    Color menuItemBgActive = new Color(77, 76, 223);

    PanelListaSimple panelListaSimple;
    PanelListaDoble panelListaDoble;
    PanelListaCircular panelListaCircular;
    PanelPila panelPila;
    PanelCola panelCola;
    PanelArbolBinario panelArbol;

    /**
     * Creates new form Bienvenido
     */
    public Bienvenido() {
        initComponents();

        panelListaSimple = new PanelListaSimple();
        panelListaDoble = new PanelListaDoble();
        panelListaCircular = new PanelListaCircular();
        panelPila = new PanelPila();
        panelCola = new PanelCola();
        panelArbol = new PanelArbolBinario();

        cambiarPanel(panelListaSimple);
        
        itemListaSimple.setBackground(menuItemBgActive);
        itemActivo = itemListaSimple;
        
        agregarEventosHover(itemListaSimple);
        agregarEventosHover(itemListaDobles);
        agregarEventosHover(itemListaCirculares);
        agregarEventosHover(itemListaPila);
        agregarEventosHover(itemSalir);
        agregarEventosHover(itemArbol);
    }

    private void cambiarPanel(JPanel panel) {
        panel.setSize(600, 600);
        panel.setLocation(0, 0);
        content.removeAll();
        content.add(panel, BorderLayout.CENTER);
        content.revalidate();
        content.repaint();
    }

    private void agregarEventosHover(JPanel item) {
        item.addMouseListener(new java.awt.event.MouseAdapter() {
            @Override
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                if (item != itemActivo)
                    item.setBackground(menuItemBgHover);
            }

            @Override
            public void mouseExited(java.awt.event.MouseEvent evt) {
                if (item != itemActivo)
                    item.setBackground(menuItemBg);
            }
        });
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        bg = new javax.swing.JPanel();
        menu = new javax.swing.JPanel();
        bienvenidoLogo = new javax.swing.JLabel();
        itemListaSimple = new javax.swing.JPanel();
        itemTextListaSimples = new javax.swing.JLabel();
        itemListaDobles = new javax.swing.JPanel();
        itemTextListasDobles = new javax.swing.JLabel();
        itemListaCirculares = new javax.swing.JPanel();
        itemTextListasCirculares = new javax.swing.JLabel();
        itemListaPila = new javax.swing.JPanel();
        itemTextListasPila = new javax.swing.JLabel();
        itemListaCola = new javax.swing.JPanel();
        itemTextListasCola = new javax.swing.JLabel();
        itemArbol = new javax.swing.JPanel();
        itemTextArbol = new javax.swing.JLabel();
        itemSalir = new javax.swing.JPanel();
        itemTextSalir = new javax.swing.JLabel();
        content = new javax.swing.JPanel();

        bg.setBackground(new java.awt.Color(21, 94, 163));
        bg.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        menu.setBackground(new java.awt.Color(50, 51, 128));
        menu.setPreferredSize(new java.awt.Dimension(300, 600));
        menu.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        bienvenidoLogo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/isologo_white.png"))); // NOI18N
        bienvenidoLogo.setAlignmentY(0.0F);
        bienvenidoLogo.setAutoscrolls(true);
        menu.add(bienvenidoLogo, new org.netbeans.lib.awtextra.AbsoluteConstraints(19, 18, -1, 42));

        itemListaSimple.setBackground(new java.awt.Color(36, 173, 219));
        itemListaSimple.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        itemListaSimple.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                itemListaSimpleMouseClicked(evt);
            }
        });

        itemTextListaSimples.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        itemTextListaSimples.setForeground(new java.awt.Color(255, 255, 255));
        itemTextListaSimples.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/icons/square.png"))); // NOI18N
        itemTextListaSimples.setText("Listas simples");
        itemTextListaSimples.setIconTextGap(16);

        javax.swing.GroupLayout itemListaSimpleLayout = new javax.swing.GroupLayout(itemListaSimple);
        itemListaSimple.setLayout(itemListaSimpleLayout);
        itemListaSimpleLayout.setHorizontalGroup(
            itemListaSimpleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(itemListaSimpleLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(itemTextListaSimples)
                .addContainerGap(157, Short.MAX_VALUE))
        );
        itemListaSimpleLayout.setVerticalGroup(
            itemListaSimpleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(itemListaSimpleLayout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addComponent(itemTextListaSimples)
                .addContainerGap(19, Short.MAX_VALUE))
        );

        menu.add(itemListaSimple, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 80, -1, -1));

        itemListaDobles.setBackground(new java.awt.Color(50, 51, 128));
        itemListaDobles.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        itemListaDobles.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                itemListaDoblesMouseClicked(evt);
            }
        });

        itemTextListasDobles.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        itemTextListasDobles.setForeground(new java.awt.Color(255, 255, 255));
        itemTextListasDobles.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/icons/squares-exclude.png"))); // NOI18N
        itemTextListasDobles.setText("Listas Dobles");
        itemTextListasDobles.setIconTextGap(16);

        javax.swing.GroupLayout itemListaDoblesLayout = new javax.swing.GroupLayout(itemListaDobles);
        itemListaDobles.setLayout(itemListaDoblesLayout);
        itemListaDoblesLayout.setHorizontalGroup(
            itemListaDoblesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(itemListaDoblesLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(itemTextListasDobles)
                .addContainerGap(160, Short.MAX_VALUE))
        );
        itemListaDoblesLayout.setVerticalGroup(
            itemListaDoblesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(itemListaDoblesLayout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addComponent(itemTextListasDobles)
                .addContainerGap(19, Short.MAX_VALUE))
        );

        menu.add(itemListaDobles, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 140, -1, -1));

        itemListaCirculares.setBackground(new java.awt.Color(50, 51, 128));
        itemListaCirculares.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        itemListaCirculares.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                itemListaCircularesMouseClicked(evt);
            }
        });

        itemTextListasCirculares.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        itemTextListasCirculares.setForeground(new java.awt.Color(255, 255, 255));
        itemTextListasCirculares.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/icons/circle.png"))); // NOI18N
        itemTextListasCirculares.setText("Listas Circulares");
        itemTextListasCirculares.setIconTextGap(16);

        javax.swing.GroupLayout itemListaCircularesLayout = new javax.swing.GroupLayout(itemListaCirculares);
        itemListaCirculares.setLayout(itemListaCircularesLayout);
        itemListaCircularesLayout.setHorizontalGroup(
            itemListaCircularesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(itemListaCircularesLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(itemTextListasCirculares)
                .addContainerGap(143, Short.MAX_VALUE))
        );
        itemListaCircularesLayout.setVerticalGroup(
            itemListaCircularesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(itemListaCircularesLayout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addComponent(itemTextListasCirculares)
                .addContainerGap(19, Short.MAX_VALUE))
        );

        menu.add(itemListaCirculares, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 200, -1, -1));

        itemListaPila.setBackground(new java.awt.Color(50, 51, 128));
        itemListaPila.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        itemListaPila.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                itemListaPilaMouseClicked(evt);
            }
        });

        itemTextListasPila.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        itemTextListasPila.setForeground(new java.awt.Color(255, 255, 255));
        itemTextListasPila.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/icons/layers-2.png"))); // NOI18N
        itemTextListasPila.setText("Pila (LIFO)");
        itemTextListasPila.setIconTextGap(16);

        javax.swing.GroupLayout itemListaPilaLayout = new javax.swing.GroupLayout(itemListaPila);
        itemListaPila.setLayout(itemListaPilaLayout);
        itemListaPilaLayout.setHorizontalGroup(
            itemListaPilaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(itemListaPilaLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(itemTextListasPila)
                .addContainerGap(178, Short.MAX_VALUE))
        );
        itemListaPilaLayout.setVerticalGroup(
            itemListaPilaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(itemListaPilaLayout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addComponent(itemTextListasPila)
                .addContainerGap(19, Short.MAX_VALUE))
        );

        menu.add(itemListaPila, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 260, 300, -1));

        itemListaCola.setBackground(new java.awt.Color(50, 51, 128));
        itemListaCola.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        itemListaCola.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                itemListaColaMouseClicked(evt);
            }
        });

        itemTextListasCola.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        itemTextListasCola.setForeground(new java.awt.Color(255, 255, 255));
        itemTextListasCola.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/icons/horizontal-end.png"))); // NOI18N
        itemTextListasCola.setText("Cola (FIFO)");
        itemTextListasCola.setIconTextGap(16);

        javax.swing.GroupLayout itemListaColaLayout = new javax.swing.GroupLayout(itemListaCola);
        itemListaCola.setLayout(itemListaColaLayout);
        itemListaColaLayout.setHorizontalGroup(
            itemListaColaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(itemListaColaLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(itemTextListasCola)
                .addContainerGap(172, Short.MAX_VALUE))
        );
        itemListaColaLayout.setVerticalGroup(
            itemListaColaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(itemListaColaLayout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addComponent(itemTextListasCola)
                .addContainerGap(19, Short.MAX_VALUE))
        );

        menu.add(itemListaCola, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 320, 300, -1));

        itemArbol.setBackground(new java.awt.Color(50, 51, 128));
        itemArbol.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        itemArbol.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                itemArbolMouseClicked(evt);
            }
        });

        itemTextArbol.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        itemTextArbol.setForeground(new java.awt.Color(255, 255, 255));
        itemTextArbol.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/icons/network.png"))); // NOI18N
        itemTextArbol.setText("Arbol Binario");
        itemTextArbol.setIconTextGap(16);

        javax.swing.GroupLayout itemArbolLayout = new javax.swing.GroupLayout(itemArbol);
        itemArbol.setLayout(itemArbolLayout);
        itemArbolLayout.setHorizontalGroup(
            itemArbolLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(itemArbolLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(itemTextArbol)
                .addContainerGap(161, Short.MAX_VALUE))
        );
        itemArbolLayout.setVerticalGroup(
            itemArbolLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(itemArbolLayout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addComponent(itemTextArbol)
                .addContainerGap(19, Short.MAX_VALUE))
        );

        menu.add(itemArbol, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 380, -1, -1));

        itemSalir.setBackground(new java.awt.Color(50, 51, 128));
        itemSalir.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        itemSalir.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                itemSalirMouseClicked(evt);
            }
        });

        itemTextSalir.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        itemTextSalir.setForeground(new java.awt.Color(255, 255, 255));
        itemTextSalir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/icons/door-open.png"))); // NOI18N
        itemTextSalir.setText("Salir");
        itemTextSalir.setIconTextGap(16);

        javax.swing.GroupLayout itemSalirLayout = new javax.swing.GroupLayout(itemSalir);
        itemSalir.setLayout(itemSalirLayout);
        itemSalirLayout.setHorizontalGroup(
            itemSalirLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(itemSalirLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(itemTextSalir)
                .addContainerGap(215, Short.MAX_VALUE))
        );
        itemSalirLayout.setVerticalGroup(
            itemSalirLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(itemSalirLayout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addComponent(itemTextSalir)
                .addContainerGap(19, Short.MAX_VALUE))
        );

        menu.add(itemSalir, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 440, -1, -1));

        bg.add(menu, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 300, -1));

        content.setBackground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout contentLayout = new javax.swing.GroupLayout(content);
        content.setLayout(contentLayout);
        contentLayout.setHorizontalGroup(
            contentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 600, Short.MAX_VALUE)
        );
        contentLayout.setVerticalGroup(
            contentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 600, Short.MAX_VALUE)
        );

        bg.add(content, new org.netbeans.lib.awtextra.AbsoluteConstraints(302, 0, 600, 600));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(bg, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(bg, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void itemListaSimpleMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_itemListaSimpleMouseClicked
        // TODO add your handling code here:
        cambiarPanel(panelListaSimple);
        cambiarActivo(itemListaSimple);
    }//GEN-LAST:event_itemListaSimpleMouseClicked

    private void itemSalirMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_itemSalirMouseClicked
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_itemSalirMouseClicked

    private void itemListaDoblesMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_itemListaDoblesMouseClicked
        // TODO add your handling code here:
        cambiarPanel(panelListaDoble);
        cambiarActivo(itemListaDobles);
    }//GEN-LAST:event_itemListaDoblesMouseClicked

    private void itemListaCircularesMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_itemListaCircularesMouseClicked
        // TODO add your handling code here:
        cambiarPanel(panelListaCircular);
        cambiarActivo(itemListaCirculares);                
    }//GEN-LAST:event_itemListaCircularesMouseClicked

    private void itemListaPilaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_itemListaPilaMouseClicked
        // TODO add your handling code here:
        cambiarPanel(panelPila);
        cambiarActivo(itemListaPila);
    }//GEN-LAST:event_itemListaPilaMouseClicked

    private void itemListaColaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_itemListaColaMouseClicked
        // TODO add your handling code here:
        cambiarPanel(panelCola);
        cambiarActivo(itemListaCola);
    }//GEN-LAST:event_itemListaColaMouseClicked

    private void itemArbolMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_itemArbolMouseClicked
        // TODO add your handling code here:
        cambiarPanel(panelArbol);
        cambiarActivo(itemArbol);
    }//GEN-LAST:event_itemArbolMouseClicked

    private void cambiarActivo(JPanel item) {
        if (itemActivo != item) {
            item.setBackground(menuItemBgActive);
            itemActivo.setBackground(menuItemBg);
            itemActivo = item;
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel bg;
    private javax.swing.JLabel bienvenidoLogo;
    private javax.swing.JPanel content;
    private javax.swing.JPanel itemArbol;
    private javax.swing.JPanel itemListaCirculares;
    private javax.swing.JPanel itemListaCola;
    private javax.swing.JPanel itemListaDobles;
    private javax.swing.JPanel itemListaPila;
    private javax.swing.JPanel itemListaSimple;
    private javax.swing.JPanel itemSalir;
    private javax.swing.JLabel itemTextArbol;
    private javax.swing.JLabel itemTextListaSimples;
    private javax.swing.JLabel itemTextListasCirculares;
    private javax.swing.JLabel itemTextListasCola;
    private javax.swing.JLabel itemTextListasDobles;
    private javax.swing.JLabel itemTextListasPila;
    private javax.swing.JLabel itemTextSalir;
    private javax.swing.JPanel menu;
    // End of variables declaration//GEN-END:variables
}
