/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package proyecto.vistas;

import java.awt.Dimension;
import javax.swing.Box;
import javax.swing.BoxLayout;

import javax.swing.JLabel;
import javax.swing.JSpinner;

import proyecto.algoritmos.*;
import proyecto.componentes.*;
import proyecto.utils.*;

/**
 *
 * @author ABEL
 */
public class PanelPila extends javax.swing.JPanel {

    private final Lista lista = new Lista();
    private String[] arreglo = null;
    private int contador = 0;
    private boolean arregloActivo = false;

    /**
     * Creates new form Inicio
     */
    public PanelPila() {
        initComponents();
        spinnerArregloSize.setEditor(new JSpinner.DefaultEditor(spinnerArregloSize));
        spinnerArregloSize.setFocusable(false);
    }

    public void configurarArreglo() {
        boolean hayArreglo = (arreglo != null);
        
        botonSetArreglo.setEnabled(!hayArreglo);
        spinnerArregloSize.setEnabled(!hayArreglo);
        nuevoValorArreglo.setEnabled(hayArreglo);
        botonPushArreglo.setEnabled(hayArreglo);
        botonPopArreglo.setEnabled(hayArreglo);
        botonRemoveArreglo.setEnabled(hayArreglo);
    }

    private void renderNodos() {
        visorPanel.removeAll();
        visorPanel.setLayout(new BoxLayout(visorPanel, BoxLayout.Y_AXIS));

        visorPanel.add(Box.createVerticalGlue());

        Nodo actual = lista.getCabeza();

        while (actual != null) {
            String idActual = actual.toString();
            String enlace = actual.enlace != null ? actual.enlace.toString() : "null";

            PanelNodo nodoPanel = new PanelNodo(actual.informacion, enlace, idActual);
            Panel.lockSize(nodoPanel);

            visorPanel.add(nodoPanel, 1);

            if (actual.enlace != null) {
                JLabel flecha = Label.crear("↑");
                visorPanel.add(flecha, 1);
            }

            actual = actual.enlace;
        }

        visorPanel.revalidate();
        visorPanel.repaint();
    }

    private void renderArreglo() {
        visorPanel.removeAll();

        if (arreglo != null) {
            visorPanel.setLayout(new BoxLayout(visorPanel, BoxLayout.Y_AXIS));
            visorPanel.add(Box.createVerticalGlue());

            for (String pila1 : arreglo) {
                PanelArreglo panelArreglo = new PanelArreglo(pila1);
                Dimension pref = panelArreglo.getPreferredSize();
                panelArreglo.setMaximumSize(pref);
                panelArreglo.setMinimumSize(pref);
                visorPanel.add(panelArreglo, 1);
            }
        }

        visorPanel.revalidate();
        visorPanel.repaint();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        pageTitle = new javax.swing.JLabel();
        visorLista = new javax.swing.JScrollPane();
        visorPanel = new javax.swing.JPanel();
        titleSeccion = new javax.swing.JLabel();
        mostrarLista = new javax.swing.JButton();
        separador = new javax.swing.JSeparator();
        tabsTipo = new javax.swing.JTabbedPane();
        tabLista = new javax.swing.JPanel();
        botonPop = new javax.swing.JButton();
        botonPush = new javax.swing.JButton();
        nuevoValor = new javax.swing.JTextField();
        labelValor = new javax.swing.JLabel();
        tabArreglo = new javax.swing.JPanel();
        labelArregloSize = new javax.swing.JLabel();
        spinnerArregloSize = new javax.swing.JSpinner();
        botonPopArreglo = new javax.swing.JButton();
        botonPushArreglo = new javax.swing.JButton();
        nuevoValorArreglo = new javax.swing.JTextField();
        labelValorArreglo = new javax.swing.JLabel();
        botonSetArreglo = new javax.swing.JButton();
        botonRemoveArreglo = new javax.swing.JButton();

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        pageTitle.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        pageTitle.setText("Pila (LIFO)");
        jPanel1.add(pageTitle, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 10, -1, -1));

        visorLista.setBackground(new java.awt.Color(218, 218, 240));
        visorLista.setBorder(null);
        visorLista.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);
        visorLista.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_ALWAYS);
        visorLista.setAutoscrolls(true);
        visorLista.setFocusable(false);

        visorPanel.setBackground(new java.awt.Color(245, 243, 255));
        visorPanel.setBorder(javax.swing.BorderFactory.createEmptyBorder(14, 14, 14, 14));
        visorPanel.setLayout(new javax.swing.BoxLayout(visorPanel, javax.swing.BoxLayout.X_AXIS));
        visorLista.setViewportView(visorPanel);

        jPanel1.add(visorLista, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 180, 600));

        titleSeccion.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        titleSeccion.setText("Algoritmos Pila con Lista");
        jPanel1.add(titleSeccion, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 70, -1, -1));

        mostrarLista.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        mostrarLista.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/icons/file-scan.png"))); // NOI18N
        mostrarLista.setToolTipText("Ejecutar toString()");
        mostrarLista.setBorder(null);
        mostrarLista.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        mostrarLista.setFocusable(false);
        mostrarLista.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mostrarListaActionPerformed(evt);
            }
        });
        jPanel1.add(mostrarLista, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 0, 40, 40));

        separador.setForeground(new java.awt.Color(238, 238, 238));
        jPanel1.add(separador, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 40, 420, 10));

        tabsTipo.setBackground(new java.awt.Color(255, 255, 255));
        tabsTipo.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                tabsTipoStateChanged(evt);
            }
        });

        tabLista.setBackground(new java.awt.Color(255, 255, 255));
        tabLista.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        botonPop.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        botonPop.setText("Desapilar (Pop)");
        botonPop.setToolTipText("");
        botonPop.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonPopActionPerformed(evt);
            }
        });
        tabLista.add(botonPop, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 150, 240, 40));

        botonPush.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        botonPush.setText("Apilar (Push)");
        botonPush.setToolTipText("");
        botonPush.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonPushActionPerformed(evt);
            }
        });
        tabLista.add(botonPush, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 100, 240, 40));

        nuevoValor.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        nuevoValor.setToolTipText("");
        tabLista.add(nuevoValor, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 50, 240, 30));

        labelValor.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        labelValor.setText("Ingrese el valor a insertar");
        tabLista.add(labelValor, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 20, -1, -1));

        tabsTipo.addTab("Pila con Lista", tabLista);

        tabArreglo.setBackground(new java.awt.Color(255, 255, 255));
        tabArreglo.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        labelArregloSize.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        labelArregloSize.setText("Defina el tamaño del arreglo");
        tabArreglo.add(labelArregloSize, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 20, -1, -1));

        spinnerArregloSize.setModel(new javax.swing.SpinnerNumberModel(5, 1, 20, 1));
        tabArreglo.add(spinnerArregloSize, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 50, 240, 30));

        botonPopArreglo.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        botonPopArreglo.setText("Desapilar (Pop)");
        botonPopArreglo.setToolTipText("");
        botonPopArreglo.setEnabled(false);
        botonPopArreglo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonPopArregloActionPerformed(evt);
            }
        });
        tabArreglo.add(botonPopArreglo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 290, 240, 40));

        botonPushArreglo.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        botonPushArreglo.setText("Apilar (Push)");
        botonPushArreglo.setToolTipText("");
        botonPushArreglo.setEnabled(false);
        botonPushArreglo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonPushArregloActionPerformed(evt);
            }
        });
        tabArreglo.add(botonPushArreglo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 240, 240, 40));

        nuevoValorArreglo.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        nuevoValorArreglo.setToolTipText("");
        nuevoValorArreglo.setEnabled(false);
        tabArreglo.add(nuevoValorArreglo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 190, 240, 30));

        labelValorArreglo.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        labelValorArreglo.setText("Ingrese el valor a insertar");
        tabArreglo.add(labelValorArreglo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 160, -1, -1));

        botonSetArreglo.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        botonSetArreglo.setText("Crear");
        botonSetArreglo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonSetArregloActionPerformed(evt);
            }
        });
        tabArreglo.add(botonSetArreglo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 100, 110, 40));

        botonRemoveArreglo.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        botonRemoveArreglo.setText("Borrar");
        botonRemoveArreglo.setEnabled(false);
        botonRemoveArreglo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonRemoveArregloActionPerformed(evt);
            }
        });
        tabArreglo.add(botonRemoveArreglo, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 100, 110, 40));

        tabsTipo.addTab("Pila con Arreglo", tabArreglo);

        jPanel1.add(tabsTipo, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 110, 360, 450));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void botonPushActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonPushActionPerformed
        // TODO add your handling code here:
        String valor = nuevoValor.getText().trim();
        lista.insertarFinal(valor);

        renderNodos();
        nuevoValor.setText("");
        nuevoValor.requestFocus();
    }//GEN-LAST:event_botonPushActionPerformed

    private void mostrarListaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mostrarListaActionPerformed
        // TODO add your handling code here:
        String datos = arregloActivo ? Arreglo.mostrarArreglo(arreglo) : lista.toString();
        String texto = "La Pila tiene: " + datos;
        Aviso.warn(texto);
    }//GEN-LAST:event_mostrarListaActionPerformed

    private void botonPopActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonPopActionPerformed
        // TODO add your handling code here:
        lista.eliminarFinal();
        renderNodos();
    }//GEN-LAST:event_botonPopActionPerformed

    private void botonPushArregloActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonPushArregloActionPerformed
        // TODO add your handling code here:
        int max = arreglo.length;
        if (contador >= max) {
          Aviso.pilaLlena(max);
          return;
        } 
        
        String valor = nuevoValorArreglo.getText().trim();

        if ("".equals(valor)) {
            Aviso.datoVacio();
            return;
        }

        arreglo[contador] = valor;
        contador++;
        
        renderArreglo();
        nuevoValorArreglo.setText("");
        nuevoValorArreglo.requestFocus();
    }//GEN-LAST:event_botonPushArregloActionPerformed

    private void botonPopArregloActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonPopArregloActionPerformed
        // TODO add your handling code here:
        if (contador <= 0) {
            Aviso.pilaVacia(contador);
            return;
        }
        
        Arreglo.eliminarUltimo(contador, arreglo);
        contador--;
        renderArreglo();
        nuevoValorArreglo.setText("");
        nuevoValorArreglo.requestFocus();
    }//GEN-LAST:event_botonPopArregloActionPerformed

    private void botonSetArregloActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonSetArregloActionPerformed
        // TODO add your handling code here:
        int longitud = (int) spinnerArregloSize.getValue();
        arreglo = new String[longitud];
        configurarArreglo();
        renderArreglo();
    }//GEN-LAST:event_botonSetArregloActionPerformed

    private void tabsTipoStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_tabsTipoStateChanged
        // TODO add your handling code here:
        if (tabsTipo.getSelectedIndex() == 0) {
            titleSeccion.setText("Algoritmos Pila con Lista");
            nuevoValor.requestFocus();
            arregloActivo = false;
            renderNodos();
        } else if (tabsTipo.getSelectedIndex() == 1) {
            titleSeccion.setText("Algoritmos Pila con Arreglo");
            nuevoValorArreglo.requestFocus();
            arregloActivo = true;
            renderArreglo();
        }
    }//GEN-LAST:event_tabsTipoStateChanged

    private void botonRemoveArregloActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonRemoveArregloActionPerformed
        // TODO add your handling code here:
        arreglo = null;
        contador = 0;
        renderArreglo();
        configurarArreglo();
    }//GEN-LAST:event_botonRemoveArregloActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botonPop;
    private javax.swing.JButton botonPopArreglo;
    private javax.swing.JButton botonPush;
    private javax.swing.JButton botonPushArreglo;
    private javax.swing.JButton botonRemoveArreglo;
    private javax.swing.JButton botonSetArreglo;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel labelArregloSize;
    private javax.swing.JLabel labelValor;
    private javax.swing.JLabel labelValorArreglo;
    private javax.swing.JButton mostrarLista;
    private javax.swing.JTextField nuevoValor;
    private javax.swing.JTextField nuevoValorArreglo;
    private javax.swing.JLabel pageTitle;
    private javax.swing.JSeparator separador;
    private javax.swing.JSpinner spinnerArregloSize;
    private javax.swing.JPanel tabArreglo;
    private javax.swing.JPanel tabLista;
    private javax.swing.JTabbedPane tabsTipo;
    private javax.swing.JLabel titleSeccion;
    private javax.swing.JScrollPane visorLista;
    private javax.swing.JPanel visorPanel;
    // End of variables declaration//GEN-END:variables
}
